# Generated by Django 5.0.14 on 2025-05-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfItemValue',
            fields=[
                ('valueID', models.AutoField(primary_key=True, serialize=False)),
                ('listID', models.IntegerField()),
                ('descriptionValue', models.CharField(max_length=100)),
                ('itemValue', models.CharField(max_length=20)),
                ('hsValue', models.CharField(max_length=50)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_by', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
