from django.db import models

class Customer(models.Model):
    id = models.CharField(primary_key=True, max_length=50)
    type = models.CharField(max_length=100, null=True)
    firstname = models.CharField(max_length=255, null=True)
    lastname = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=255, null=True)
    deal_id = models.CharField(max_length=50, null=True)
    address = models.CharField(max_length=255, null=True)
    streetName = models.CharField(max_length=255, null=True)
    streetNumber = models.CharField(max_length=10, null=True)
    districtName = models.CharField(max_length=100, null=True)
    residency = models.CharField(max_length=100, null=True)
    zipCode = models.CharField(max_length=100, null=True)
    zip = models.CharField(max_length=255, null=True)
    nit = models.CharField(max_length=255, null=True)
    gender = models.CharField(max_length=255, null=True)
    pais_nacimiento = models.CharField(max_length=255, null=True)
    prefix = models.CharField(max_length=5, null=True)
    phone = models.CharField(max_length=255, null=True)
    canal = models.CharField(max_length=255, null=True)
    industry = models.CharField(max_length=255, null=True)
    date_of_birth = models.CharField(max_length=255, null=True)
    nacionalidad_c = models.CharField(max_length=255, null=True)
    organizacion_de_ventas = models.CharField(max_length=255, null=True)
    vecindad = models.CharField(max_length=255, null=True)
    rango_de_ingresos_mensuales = models.CharField(max_length=255, null=True)
    rango_de_egresos = models.CharField(max_length=255, null=True)
    fuente_de_ingreso = models.CharField(max_length=255, null=True)
    cantidad_de_personas_dependientes = models.CharField(max_length=255, null=True)
    mascota_yn = models.CharField(max_length=1, null=True)
    tipo_mascota = models.CharField(max_length=255, null=True)
    contacto_fallecimiento = models.CharField(max_length=255, null=True)
    id_parentesco = models.IntegerField()
    beneficiario_final = models.CharField(max_length=255, null=True)
    relacion_gobierno = models.CharField(max_length=1, null=True)
    forma_de_pago = models.IntegerField()
    datos_complementarios = models.CharField(max_length=255, null=True)
    datos_comerciales = models.CharField(max_length=255, null=True)
    lugar_de_trabajo = models.CharField(max_length=255, null=True)    
    numero_de_bp = models.CharField(max_length=255, null=True)
    observaciones = models.CharField(max_length=255, null=True)
    create_at = models.DateTimeField(null=True)
    status_update = models.BooleanField(null=True)

    class Meta:
        db_table = 'Customer'
        managed = False